PRODUCTS = {
    "Groceries & Food Items": {
        "Onions (1kg)": 30,
        "Potatoes (1kg)": 25,
        "Tomatoes (1kg)": 35,
        "Green Chilies (100g)": 10,
        "Garlic (100g)": 15,
        "Ginger (100g)": 12,
        "Turmeric Powder (100g)": 20,
        "Red Chili Powder (100g)": 25,
        "Coriander Powder (100g)": 20,
        "Masala Pack": 35,
        "Dal (1kg)": 90,
        "Poha (500g)": 30,
        "Suji (500g)": 25,
        "Rice (1kg)": 60,
        "Wheat Flour (1kg)": 55,
        "Sugar (1kg)": 45,
        "Salt (1kg)": 20,
        "Cooking Oil (1L)": 120,
        "Tea (250g)": 90,
        "Milk Packet": 50,
        "Eggs (Dozen)": 70,
        "Bread Loaf": 40,
    },
    "Snacks & Packaged Food": {
        "Biscuit Packet": 25,
        "Cream Biscuit Packet": 30,
        "Marie Biscuit Packet": 20,
        "Instant Noodles": 15,
        "Macaroni/Pasta": 30,
        "Chips": 30,
        "Namkeen Packet": 25,
        "Chocolate Bar": 40,
        "Ice Cream Cup/Stick": 60,
        "Tetra Pack Juice": 30,
        "Chip Packet": 20,
    },
    "Personal Care": {
        "Soap Bar": 30,
        "Shampoo (100ml)": 60,
        "Shampoo (200ml)": 110,
        "Face Cream (50g)": 80,
        "Body Lotion (100ml)": 90,
        "Toothpaste (100g)": 45,
        "Toothbrush": 20,
        "Hair Oil (100ml)": 50,
        "Sanitary Napkins": 40,
        "Comb": 15,
        "Nail Cutter": 20,
    },
    "Household & Cleaning": {
        "Detergent Powder (500g)": 45,
        "Dishwashing Liquid (250ml)": 40,
        "Scrubber Pad": 10,
        "Matchbox": 2,
        "Mosquito Coil/Mat": 40,
        "Room Freshener": 90,
        "Garbage Bags": 30,
        "Floor Cleaner (500ml)": 60,
        "Toilet Cleaner": 50,
        "CFL Bulb": 60,
        "AA Battery": 20,
        "Button Cell Battery": 15,
    },
    "Kitchenware": {
        "Steel Plate": 120,
        "Nonstick Pan": 350,
        "Glass Tumbler": 60,
        "Plastic Bowl": 30,
        "Ceramic Mug": 80,
        "Wooden Spoon": 25,
        "Stainless Steel Bottle": 300,
        "Reusable Lunch Box": 200,
    },
    "Stationery": {
        "Ball Pen": 10,
        "Pencil": 5,
        "Notebook (100pg)": 40,
        "Notebook (200pg)": 60,
        "Eraser": 3,
        "Sharpener": 5,
        "Ruler": 8,
        "Glue Stick": 15,
        "Marker Pen": 20,
        "Stapler": 30,
        "Color Pencils": 40,
        "Highlighter Pen": 20,
        "Scissors": 30,
        "Tape": 15,
    }
}